#!/usr/bin/env pwsh
# Generates libkg/apisecrets.h, which libkg.pri lists in HEADERS and the build
# cannot link without. The file is gitignored and must never be committed.
#
# Precedence, highest first (mirrors TelegramJ2ME/tools/_env.ps1):
#   1. environment: TG_API_ID / TG_API_HASH
#   2. secrets/telegram.yaml
#
# Upstream shipped fillSecrets.bat, which appends with `echo >>` and so emits a
# duplicate-macro file when run twice. This overwrites atomically instead.

[CmdletBinding()]
param(
    [string] $Root = (Split-Path -Parent $PSScriptRoot),
    [switch] $Quiet
)

$ErrorActionPreference = 'Stop'

$outFile  = Join-Path $Root 'libkg/apisecrets.h'
$yamlFile = Join-Path $Root 'secrets/telegram.yaml'

function Read-FlatYaml([string] $Path) {
    $map = @{}
    if (-not (Test-Path $Path)) { return $map }
    foreach ($line in Get-Content -LiteralPath $Path) {
        $t = $line.Trim()
        if ($t -eq '' -or $t.StartsWith('#')) { continue }
        $i = $t.IndexOf(':')
        if ($i -lt 1) { continue }
        $k = $t.Substring(0, $i).Trim()
        $v = $t.Substring($i + 1).Trim().Trim('"', "'")
        $map[$k] = $v
    }
    return $map
}

$yaml = Read-FlatYaml $yamlFile

$apiId   = if ($env:TG_API_ID)   { $env:TG_API_ID }   else { $yaml['api_id'] }
$apiHash = if ($env:TG_API_HASH) { $env:TG_API_HASH } else { $yaml['api_hash'] }
$source  = if ($env:TG_API_ID)   { 'environment' }    else { 'secrets/telegram.yaml' }

if ([string]::IsNullOrWhiteSpace($apiId) -or [string]::IsNullOrWhiteSpace($apiHash)) {
    throw "No Telegram credentials found. Set TG_API_ID/TG_API_HASH, or copy " +
          "config/telegram.yaml.example to secrets/telegram.yaml and fill it in. " +
          "Register an app at https://my.telegram.org."
}

$idInt = 0
if (-not [int]::TryParse($apiId, [ref] $idInt) -or $idInt -le 0) {
    throw "api_id must be a positive integer (got '$apiId'). A zero api_id compiles but every API call fails."
}
if ($apiHash -notmatch '^[0-9a-fA-F]{32}$') {
    throw "api_hash must be 32 hex characters (got length $($apiHash.Length))."
}

$body = @"
#ifndef APISECRETS_H
#define APISECRETS_H

/* GENERATED by tools/write-apisecrets.ps1 -- do not edit, do not commit.
   Source: $source */

#define SYMBOGRAM_API_ID $idInt
#define SYMBOGRAM_API_HASH "$apiHash"

#endif // APISECRETS_H
"@

# Atomic: a half-written header must never reach the compiler.
New-Item -ItemType Directory -Force (Split-Path -Parent $outFile) | Out-Null
$tmp = "$outFile.tmp"
Set-Content -LiteralPath $tmp -Value $body -Encoding UTF8 -NoNewline
Move-Item -LiteralPath $tmp -Destination $outFile -Force

if (-not $Quiet) {
    # Print a digest, never the credentials themselves -- this output lands in
    # build logs and CI transcripts. Same discipline as J2MEgram's
    # Format-SecretDigest in tools/_env.ps1.
    $digest = (Get-FileHash -Algorithm SHA256 -LiteralPath $outFile).Hash.Substring(0, 12)
    Write-Host "apisecrets.h written from $source (sha256:$digest)"
    $title = $yaml['app_title']
    if ($title -and $title -ne 'SymboGram') {
        Write-Warning ("These credentials are registered to '$title', not SymboGram. Fine for " +
                       "development; register a SymboGram app at https://my.telegram.org before any " +
                       "public release, or risk API_ID_PUBLISHED_FLOOD taking down both projects.")
    }
}
